stages:
- test
- name: deploy
  if: tag IS present AND fork = false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - python setup.py -q install

jobs:
  include:
  - stage: deploy
    python: '3.6'
    script: skip
    deploy:
      stage: deploy
      provider: pypi
      on:
        tags: true
      distributions: sdist bdist_wheel
      user: reportportal
      password:
        secure: nhpdigpcYQcvN6ilunCO3cIvNi3t/cyZM+ayqeq5y/1cZnnk9HEl5dVtj9zIl+EpWd6gCg8fexDVO/zekd6DXBypE4hkNqZJ/5+jeA9DOz/rrUjAAKpgIOxncXX6xms6/8UXEqIaNL4rhqzU4oQ6FBTAp8AeyUX+OPdkTWxdlIuz2KBhgqG+89VGcgzDInvymETnvBe+DlQUWGefLoOFsevHjDmk3oByWNDNVTiDbDQtIC9odLT3mivHJj6mHVehiouXuGazBLsUmgR7yo8w7tDGn3XiKCDxfzU74Ks07LxKsoqnB3rDmmCEBaYLCZE+TZbQEZRkTHughwZhY8qBsl1WLG3wE7uYk/SeUhAnGfuPfgi/NURKM20uHSdpmIpwuMT9w+p+KtgUvQX2fnh10wtReXhr/N6qvTVRHgOZFlvMg+QyKl8dTewH/3TlhW0/IN7axZT4191f5fzlJ3rbsP9zoWS/FszB+kxVkAfxKqrA388kE527rZpT6wkHp++OkRtjW6SW1m+j+/9pYgAGJ+OATfr45Yc/QpR8u3XtyE2toeK8fGTq5TV97SNOnL74iGLiUHvIvUY8co7dlouJMN5OkJ7YytljSxJoHfwfDMo1mO8Kb3Eu+q6yHE61tOkbWBdCpPtvtoBL8q72XXy4HuIHTdWRZjHA6POPmw40fTw=
